Catalog bug: create view failed to mark base table as modified (#1370)
Due to an error in view creation, Catalog would fail to invalidate a
modified but not persisted `TableVersion`. Later that would result in
Pixeltable acting on that stale `TableVersion`, which can cause various
sorts of issues including a data corruption or the following assertion
error found by random_ops test.

For more details and repro, see the new test case.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/tool/random_ops.py", line 467, in run
    ops.run()
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/tool/random_ops.py", line 436, in run
    self.random_op()
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/tool/random_ops.py", line 430, in random_op
    self.run_op(op)
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/tool/random_ops.py", line 423, in run_op
    raise fatal
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/tool/random_ops.py", line 406, in run_op
    result = op()
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/tool/random_ops.py", line 258, in query
    res = t.sample(n=num_rows).collect()
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/pixeltable/_query.py", line 797, in collect
    return self._collect()
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/pixeltable/_query.py", line 801, in _collect
    return ResultSet(list(self.cursor()), self.schema)
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/pixeltable/_query.py", line 339, in __iter__
    for data in self._row_iterator:
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/pixeltable/_query.py", line 784, in _output_row_iterator
    with get_runtime().catalog.begin_xact(for_write=False, read_tvps=self._from_clause.tbls):
  File "/Users/sergeymkhitaryan/miniforge3/envs/pxt/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/pixeltable/catalog/catalog.py", line 396, in begin_xact
    self.validate()
  File "/Users/sergeymkhitaryan/work/pixeltable-wt-catalog/pixeltable/catalog/catalog.py", line 290, in validate
    raise AssertionError(
AssertionError: view_2 (4d75c5ef-47c2-4587-8c35-622317e9e486) missing in  ()
```

Also updates `_finalize_pending_ops()` and `_drop_tbl()` to mark tv as
modified before actually modifying in order to avoid similar issues.